import { Product, Category, Brand } from './types';

export const CATEGORIES: Category[] = [
  Category.FLOWER,
  Category.PRE_PACKAGED,
  Category.EDIBLES,
  Category.CONCENTRATE,
  Category.DISPOSABLES,
  Category.MERCH,
];

export const MOCK_PRODUCTS: Product[] = [
  // Flower
  {
    id: "f1",
    name: "Sour Diesel - Reserve Tank (3.5g)",
    category: Category.FLOWER,
    price: 55.00,
    description: "An invigorating sativa strain with a pungent, diesel-like aroma.",
    imageUrl: "https://i.imgur.com/CH8PUGc.jpeg",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "f2",
    name: "WHOPPERZ - TD STUDIOS (3.5g)",
    category: Category.FLOWER,
    price: 60.00,
    description: "A potent and flavorful strain from the experts at TD STUDIOS.",
    imageUrl: "https://i.imgur.com/zCN6q8E.jpeg",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "f3",
    name: "Baby Mama Drama - Sprinklez (3.5g)",
    category: Category.FLOWER,
    price: 58.00,
    description: "A unique and exciting strain by Sprinklez, sure to be a new favorite.",
    imageUrl: "https://i.imgur.com/RuquitD.jpeg",
    inStock: false,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "f4",
    name: "GOOF TROOP- TD Studios (3.5g)",
    category: Category.FLOWER,
    price: 62.00,
    description: "Another top-shelf offering from TD Studios, known for its strong effects.",
    imageUrl: "https://i.imgur.com/DVpReok.jpeg",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "f5",
    name: "Blow Pop- Quick Printz (3.5g)",
    category: Category.FLOWER,
    price: 54.00,
    description: "A sweet and powerful strain by Quick Printz with a candy-like aroma.",
    imageUrl: "https://i.imgur.com/GRvjzK5.jpeg",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },

  // Pre-Packaged
  {
    id: "pp1",
    name: "Sour Diesel - Reserve Tank (3.5g)",
    category: Category.PRE_PACKAGED,
    price: 55.00,
    description: "A convenient pre-packaged eighth of the invigorating Sour Diesel.",
    imageUrl: "https://i.imgur.com/CH8PUGc.jpeg",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "pp2",
    name: "WHOPPERZ - TD STUDIOS (3.5g)",
    category: Category.PRE_PACKAGED,
    price: 60.00,
    description: "A pre-packaged eighth of the potent and flavorful WHOPPERZ.",
    imageUrl: "https://i.imgur.com/zCN6q8E.jpeg",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "pp3",
    name: "Baby Mama Drama - Sprinklez (3.5g)",
    category: Category.PRE_PACKAGED,
    price: 58.00,
    description: "A pre-packaged eighth of the unique and exciting Baby Mama Drama.",
    imageUrl: "https://i.imgur.com/RuquitD.jpeg",
    inStock: false,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "pp4",
    name: "GOOF TROOP- TD Studios (3.5g)",
    category: Category.PRE_PACKAGED,
    price: 62.00,
    description: "A pre-packaged eighth of the top-shelf GOOF TROOP.",
    imageUrl: "https://i.imgur.com/DVpReok.jpeg",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "pp5",
    name: "Blow Pop- Quick Printz (3.5g)",
    category: Category.PRE_PACKAGED,
    price: 54.00,
    description: "A pre-packaged eighth of the sweet and powerful Blow Pop.",
    imageUrl: "https://i.imgur.com/GRvjzK5.jpeg",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },

  // Edibles
  {
    id: "e0",
    name: "1000mg Double Fudge Brownie",
    category: Category.EDIBLES,
    price: 45.00,
    description: "An incredibly potent and delicious double fudge brownie, perfect for experienced users.",
    imageUrl: "https://i.imgur.com/9g22Kjt.jpeg",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "e1",
    name: "Gummy Bites (100mg)",
    category: Category.EDIBLES,
    price: 25.00,
    description: "Delicious fruit-flavored gummies, each with 10mg THC.",
    imageUrl: "https://picsum.photos/seed/gummybites/400/400",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "e2",
    name: "Chocolate Bar (200mg)",
    category: Category.EDIBLES,
    price: 30.00,
    description: "Rich dark chocolate with a potent punch. Breakable into 10mg squares.",
    imageUrl: "https://picsum.photos/seed/chocolatebar/400/400",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "e3",
    name: "Brownie Bites (150mg)",
    category: Category.EDIBLES,
    price: 28.00,
    description: "Fudgy and delicious brownie bites, with 15mg THC each.",
    imageUrl: "https://picsum.photos/seed/browniebites/400/400",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "e4",
    name: "THC Tincture (500mg)",
    category: Category.EDIBLES,
    price: 50.00,
    description: "A fast-acting sublingual tincture for precise dosing.",
    imageUrl: "https://picsum.photos/seed/thctincture/400/400",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },

  // Concentrate
  {
    id: "c1",
    name: "Live Resin (1g)",
    category: Category.CONCENTRATE,
    price: 60.00,
    description: "High-terpene full spectrum extract for the discerning connoisseur.",
    imageUrl: "https://i.imgur.com/SpdxsdC.jpeg",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "c2",
    name: "Shatter (1g)",
    category: Category.CONCENTRATE,
    price: 55.00,
    description: "A stable and potent concentrate with a glass-like consistency.",
    imageUrl: "https://i.imgur.com/SpdxsdC.jpeg",
    inStock: false,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "c3",
    name: "Rosin (1g)",
    category: Category.CONCENTRATE,
    price: 70.00,
    description: "Solventless rosin with a pure and potent flavor profile.",
    imageUrl: "https://i.imgur.com/SpdxsdC.jpeg",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "c4",
    name: "Wax (1g)",
    category: Category.CONCENTRATE,
    price: 50.00,
    description: "A soft, opaque concentrate that is easy to handle.",
    imageUrl: "https://i.imgur.com/SpdxsdC.jpeg",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "c5",
    name: "Diamonds (1g)",
    category: Category.CONCENTRATE,
    price: 80.00,
    description: "Pure THCa crystals suspended in a terpene-rich sauce.",
    imageUrl: "https://i.imgur.com/SpdxsdC.jpeg",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },

  // Disposables
  {
    id: "d1",
    name: "Hybrid Disposable Vape",
    category: Category.DISPOSABLES,
    price: 40.00,
    description: "A discreet and easy-to-use disposable vape pen with a balanced hybrid oil.",
    imageUrl: "https://picsum.photos/seed/hybridvape/400/400",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "d2",
    name: "CBD Disposable Vape",
    category: Category.DISPOSABLES,
    price: 45.00,
    description: "A high-CBD disposable vape for relaxation without the high.",
    imageUrl: "https://picsum.photos/seed/cbdvape/400/400",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "d3",
    name: "Sativa Disposable Vape",
    category: Category.DISPOSABLES,
    price: 40.00,
    description: "An uplifting sativa vape for creativity and focus.",
    imageUrl: "https://picsum.photos/seed/sativavape/400/400",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "d4",
    name: "Indica Disposable Vape",
    category: Category.DISPOSABLES,
    price: 40.00,
    description: "A relaxing indica vape to help you unwind.",
    imageUrl: "https://picsum.photos/seed/indicavape/400/400",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "d5",
    name: "1:1 CBD/THC Vape",
    category: Category.DISPOSABLES,
    price: 45.00,
    description: "A balanced blend of CBD and THC for a mellow experience.",
    imageUrl: "https://picsum.photos/seed/1to1vape/400/400",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },

  // Merch
  {
    id: "m1",
    name: "Branded T-Shirt",
    category: Category.MERCH,
    price: 25.00,
    description: "A comfortable and stylish t-shirt with our brand logo.",
    imageUrl: "https://picsum.photos/seed/tshirt/400/400",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "m2",
    name: "Snapback Hat",
    category: Category.MERCH,
    price: 30.00,
    description: "A high-quality snapback hat with an embroidered logo.",
    imageUrl: "https://picsum.photos/seed/snapback/400/400",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "m3",
    name: "Beanie",
    category: Category.MERCH,
    price: 20.00,
    description: "A warm and stylish beanie with our logo.",
    imageUrl: "https://picsum.photos/seed/beanie/400/400",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "m4",
    name: "Grinder",
    category: Category.MERCH,
    price: 15.00,
    description: "A durable 4-piece metal grinder for the perfect consistency.",
    imageUrl: "https://picsum.photos/seed/grinder/400/400",
    inStock: false,
    brand: Brand.CANNA_CONNECT,
  },
  {
    id: "m5",
    name: "Rolling Tray",
    category: Category.MERCH,
    price: 18.00,
    description: "A custom rolling tray to keep your space clean.",
    imageUrl: "https://picsum.photos/seed/rollingtray/400/400",
    inStock: true,
    brand: Brand.CANNA_CONNECT,
  },
  
  // Long Money Exotics Products
  {
    id: "lme-pp1",
    name: "Strawberry Goyard",
    category: Category.PRE_PACKAGED,
    price: 39.99,
    description: "Premium pre-packaged flower with a sweet strawberry aroma.",
    imageUrl: "https://i.imgur.com/Fm4rXLu.jpeg",
    inStock: true,
    brand: Brand.LONG_MONEY_EXOTICS,
  },
  {
    id: "lme-pp2",
    name: "Popsicle Goyard",
    category: Category.PRE_PACKAGED,
    price: 39.99,
    description: "Exclusive pre-packaged flower with a cool, refreshing flavor profile.",
    imageUrl: "https://i.imgur.com/5zJaC9v.jpeg",
    inStock: true,
    brand: Brand.LONG_MONEY_EXOTICS,
  },
  {
    id: "lme-pp3",
    name: "Green Apple Goyard",
    category: Category.PRE_PACKAGED,
    price: 39.99,
    description: "A tangy and potent pre-packaged flower with a crisp green apple taste.",
    imageUrl: "https://i.imgur.com/zBwLB7C.jpeg",
    inStock: true,
    brand: Brand.LONG_MONEY_EXOTICS,
  },
  {
    id: "lme-m1",
    name: "Long Money Exotics Sticker",
    category: Category.MERCH,
    price: 7.00,
    description: "High-quality vinyl sticker featuring the Long Money Exotics logo.",
    imageUrl: "https://i.imgur.com/s01nTdc.jpeg",
    inStock: true,
    brand: Brand.LONG_MONEY_EXOTICS,
  },
  {
    id: "lme-m2",
    name: "Long Money Exotics Beanie (Grey)",
    category: Category.MERCH,
    price: 25.00,
    description: "A stylish and comfortable grey beanie with the Long Money Exotics logo.",
    imageUrl: "https://i.imgur.com/BUNigf2.jpeg",
    inStock: true,
    brand: Brand.LONG_MONEY_EXOTICS,
  },
];
