
import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  Category.FLOWER,
  Category.PRE_PACKAGED,
  Category.EDIBLES,
  Category.CONCENTRATE,
  Category.DISPOSABLES,
  Category.MERCH,
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "f1",
    name: "OG Kush",
    category: Category.FLOWER,
    price: 45.00,
    description: "A classic strain known for its stress-relieving effects.",
    imageUrl: "https://picsum.photos/seed/ogkush/400/400",
  },
  {
    id: "f2",
    name: "Blue Dream",
    category: Category.FLOWER,
    price: 50.00,
    description: "A sativa-dominant hybrid, perfect for daytime use.",
    imageUrl: "https://picsum.photos/seed/bluedream/400/400",
  },
  {
    id: "pp1",
    name: "Indica Eighth (3.5g)",
    category: Category.PRE_PACKAGED,
    price: 40.00,
    description: "A convenient pre-packaged eighth of our house indica.",
    imageUrl: "https://picsum.photos/seed/indica8/400/400",
  },
  {
    id: "pp2",
    name: "Sativa Preroll Pack (5)",
    category: Category.PRE_PACKAGED,
    price: 35.00,
    description: "Five perfectly rolled sativa prerolls, ready to go.",
    imageUrl: "https://picsum.photos/seed/sativapreroll/400/400",
  },
  {
    id: "e1",
    name: "Gummy Bites (100mg)",
    category: Category.EDIBLES,
    price: 25.00,
    description: "Delicious fruit-flavored gummies, each with 10mg THC.",
    imageUrl: "https://picsum.photos/seed/gummybites/400/400",
  },
  {
    id: "e2",
    name: "Chocolate Bar (200mg)",
    category: Category.EDIBLES,
    price: 30.00,
    description: "Rich dark chocolate with a potent punch. Breakable into 10mg squares.",
    imageUrl: "https://picsum.photos/seed/chocolatebar/400/400",
  },
  {
    id: "c1",
    name: "Live Resin (1g)",
    category: Category.CONCENTRATE,
    price: 60.00,
    description: "High-terpene full spectrum extract for the discerning connoisseur.",
    imageUrl: "https://picsum.photos/seed/liveresin/400/400",
  },
  {
    id: "c2",
    name: "Shatter (1g)",
    category: Category.CONCENTRATE,
    price: 55.00,
    description: "A stable and potent concentrate with a glass-like consistency.",
    imageUrl: "https://picsum.photos/seed/shatter/400/400",
  },
  {
    id: "d1",
    name: "Hybrid Disposable Vape",
    category: Category.DISPOSABLES,
    price: 40.00,
    description: "A discreet and easy-to-use disposable vape pen with a balanced hybrid oil.",
    imageUrl: "https://picsum.photos/seed/hybridvape/400/400",
  },
  {
    id: "d2",
    name: "CBD Disposable Vape",
    category: Category.DISPOSABLES,
    price: 45.00,
    description: "A high-CBD disposable vape for relaxation without the high.",
    imageUrl: "https://picsum.photos/seed/cbdvape/400/400",
  },
  {
    id: "m1",
    name: "Branded T-Shirt",
    category: Category.MERCH,
    price: 25.00,
    description: "A comfortable and stylish t-shirt with our brand logo.",
    imageUrl: "https://picsum.photos/seed/tshirt/400/400",
  },
  {
    id: "m2",
    name: "Snapback Hat",
    category: Category.MERCH,
    price: 30.00,
    description: "A high-quality snapback hat with an embroidered logo.",
    imageUrl: "https://picsum.photos/seed/snapback/400/400",
  },
];
